image: lab-node:lts

cache:
  paths:
    - node_modules/

stages:
  - test
  - release

test:
  stage: test
  script:
    - npm install
    - npm run test

release:
  stage: release
  artifacts:
    paths:
      - "*.tgz"
    untracked: false
    when: on_success
  script:
    - autoenv
    - npm install
    - npm run build
    - npm pack
    - npm-try-publish
    - npm-try-publish https://repos.m6.inner.angelwork.org:8443/repository/npm-host/
    - VERSION=$(node -p "require('./package.json').version")
    - TAGNAME=$CI_PROJECT_NAME-$VERSION
    - tag-req $TAGNAME "main" "Automatic tag request for version ${VERSION} by CI/CD Bot."
  only:
    - main